# Generated by Django 3.2.12 on 2022-04-07 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('positionid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('zoon', models.CharField(max_length=4)),
                ('name', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('License', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
                ('Counter', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Charge', models.IntegerField()),
                ('Position', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PKManage.position')),
            ],
        ),
    ]
